// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// APPITEM
export const APPITEM_SUCCESS = 'APPITEM_SUCCESS'
export const APPITEM_FILTER_SUCCESS = 'APPITEM_FILTER_SUCCESS'

// publish
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS'
export const UN_PUBLISH = 'UN_PUBLISH'
